# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170730_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='main location default', max_length=120),
        ),
    ]
